spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/menudb
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
    username: root
    password: 1234

logging:
  level:
    #    root: info
    com:
      ohgiraffers:
        springmybatis:
          section01:
            factorybean: debug